const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync('web/app.js', 'utf8');
const start = source.indexOf('  function handleWorkspaceNameClick(');
const end = source.indexOf('  function toggleWorkspaceExpanded(', start);
let clock = 0;
const state = { workspaceClick: null };
let folds = [], activations = [];
const sandbox = { state, performance: { now: () => clock }, toggleWorkspaceExpanded: id => folds.push(id), activateWorkspace: id => activations.push(id) };
vm.createContext(sandbox);
vm.runInContext(source.slice(start, end) + '\nthis.click = handleWorkspaceNameClick;', sandbox);
const reset = () => { state.workspaceClick = null; clock = 0; folds = []; activations = []; };
const click = (time, id='a', detail=1) => { clock=time; sandbox.click(id,{detail}); };
const cases = [];
function test(name, run) { reset(); run(); cases.push(name); }
test('single click only toggles',()=>{click(0);assert.deepEqual(folds,['a']);assert.equal(activations.length,0);});
test('rapid double click activates once',()=>{click(0);click(150);assert.deepEqual(activations,['a']);assert.equal(folds.length,1);});
test('third rapid click does not collapse activated folder',()=>{click(0);click(150);click(250);assert.deepEqual(activations,['a']);assert.equal(folds.length,1);});
test('three slower clicks activate on third',()=>{click(0);click(420);assert.equal(activations.length,0);click(840);assert.deepEqual(activations,['a']);});
test('unrelated single clicks never activate',()=>{click(0);click(700);click(1400);assert.equal(activations.length,0);assert.equal(folds.length,3);});
test('switching rows resets gesture',()=>{click(0,'a');click(80,'b');click(160,'a');assert.equal(activations.length,0);});
test('keyboard activation toggles only',()=>{click(0,'a',0);click(60,'a',0);click(120,'a',0);assert.equal(activations.length,0);assert.equal(folds.length,3);});
test('gesture expires after activation',()=>{click(0);click(100);click(900);assert.equal(activations.length,1);assert.equal(folds.length,2);});
test('mobile click events with detail one are counted',()=>{click(0,'a',1);click(100,'a',1);assert.equal(activations.length,1);});
const activateStart = source.indexOf('  function activateWorkspace(');
const activateEnd = source.indexOf('  function rememberTerminal(', activateStart);
const pending = { state: { workspaces: [{id:'pending',terminals:[]}], expanded:new Set(), lastTerminalByWorkspace:{} }, renders:0 };
pending.enterWorkspace = id => { pending.state.activeWorkspaceId = id; };
pending.selectTerminal = () => { throw new Error('unexpected terminal selection'); };
pending.renderNavigation = () => pending.renders++;
vm.createContext(pending);
vm.runInContext(source.slice(activateStart, activateEnd) + '\nactivateWorkspace(\"pending\");', pending);
assert.equal(pending.state.activeWorkspaceId, 'pending');
assert.ok(pending.state.expanded.has('pending'));
assert.equal(pending.renders, 1);
cases.push('activation renders immediately while terminal startup remains pending');
console.log(JSON.stringify({passed:cases.length,failed:0,cases},null,2));
